// Auto-extracted core tech from app.js for headless sim
export const CORE_TECH_DEFS = {

      berryCultivation: {
        name: "树果培育",
        desc: "树果产量 +50%，树果上限 +25。",
        cost: { catnip: 20 },
        prereq: [],
        req: () => true,
        timeSec: 10,
        effects: {
          catnipPerSecMul: 1.5,
          capCatnipAdd: 25,
        },
      },
      composting: {
        name: "堆肥技术",
        desc: "树果产量 +20%，树果上限 +30。",
        cost: { catnip: 45 },
        prereq: ["berryCultivation"],
        req: () => true,
        timeSec: 15,
        effects: {
          catnipPerSecMul: 1.2,
          capCatnipAdd: 30,
        },
      },
      irrigation: {
        name: "灌溉改良",
        desc: "树果产量 +25%，树果上限 +40。",
        cost: { catnip: 100 },
        prereq: ["composting"],
        req: (state) => state.buildings.field.owned >= 2,
        timeSec: 25,
        effects: {
          catnipPerSecMul: 1.25,
          capCatnipAdd: 40,
        },
      },
      greenhouse: {
        name: "温室栽培",
        desc: "树果产量 +35%，树果上限 +80。",
        cost: { catnip: 240, wood: 30 },
        prereq: ["irrigation"],
        req: (state) => state.buildings.hut.owned >= 1,
        timeSec: 40,
        effects: {
          catnipPerSecMul: 1.35,
          capCatnipAdd: 80,
        },
      },
      backpackWeaving: {
        name: "背包编织",
        desc: "树果上限 +60。",
        cost: { catnip: 70 },
        prereq: ["berryCultivation"],
        req: () => true,
        timeSec: 12,
        effects: {
          capCatnipAdd: 60,
        },
      },
      campLogistics: {
        name: "营地后勤",
        desc: "营地建筑成本 -3%，球果上限 +30。",
        cost: { catnip: 110, wood: 8 },
        prereq: ["backpackWeaving"],
        req: (state) => state.buildings.hut.owned > 0,
        timeSec: 18,
        effects: {
          buildingCostMul: 0.97,
          capWoodAdd: 30,
        },
      },
      trainerDrills: {
        name: "训练家操练",
        desc: "树果/球果/碎片产量 +10%。",
        cost: { catnip: 130 },
        prereq: ["campLogistics"],
        req: () => true,
        timeSec: 22,
        effects: {
          catnipPerSecMul: 1.1,
          woodRateMul: 1.1,
          mineralsRateMul: 1.1,
        },
      },
      pokeballBasics: {
        name: "精灵球基础",
        desc: "营地建筑成本 -5%，并解锁精灵球制作与捕捉。",
        // After TECH researchCostMul(~2): ~30 catnip — short gather burst
        cost: { catnip: 15 },
        prereq: [],
        req: () => true,
        timeSec: 4,
        effects: {
          buildingCostMul: 0.95,
          catchChanceAdd: 0.02,
        },
      },
      ballMolds: {
        name: "球壳模具",
        desc: "捕捉成功率 +1%。",
        cost: { catnip: 140, wood: 30 },
        prereq: ["pokeballBasics"],
        req: (state) => state.buildings.hut.owned > 0,
        timeSec: 18,
        effects: {
          catchChanceAdd: 0.01,
        },
      },
      apricornCrafting: {
        name: "球果工艺",
        desc: "捕捉成功率 +4%。",
        cost: { catnip: 250, wood: 80 },
        prereq: ["ballMolds"],
        req: (state) => state.buildings.hut.owned >= 2,
        effects: {
          catchChanceAdd: 0.04,
        },
      },
      reinforcedBalls: {
        name: "加固球壳",
        desc: "捕捉成功率 +6%。",
        cost: { catnip: 400, wood: 140, minerals: 30 },
        prereq: ["apricornCrafting"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          catchChanceAdd: 0.06,
        },
      },
      captureTraining: {
        name: "捕捉训练",
        desc: "捕捉成功率 +6%。",
        cost: { catnip: 600, wood: 180, minerals: 60 },
        prereq: ["reinforcedBalls"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          catchChanceAdd: 0.06,
        },
      },
      fieldResearch: {
        name: "野外观察",
        desc: "球果与进化石碎片产量 +100%，并提升对应上限。",
        cost: { catnip: 200, wood: 30 },
        prereq: ["pokeballBasics"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          woodRateMul: 2,
          mineralsRateMul: 2,
          capWoodAdd: 50,
          capMineralsAdd: 40,
          catchChanceAdd: 0.05,
        },
      },
      fieldGuide: {
        name: "野外手册",
        desc: "球果与进化石碎片产量 +25%，并提升对应上限。",
        cost: { catnip: 350, wood: 60 },
        prereq: ["fieldResearch"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          woodRateMul: 1.25,
          mineralsRateMul: 1.25,
          capWoodAdd: 80,
          capMineralsAdd: 60,
        },
      },
      mineralSurvey: {
        name: "矿脉勘测",
        desc: "进化石碎片产量 +35%，碎片上限 +60。",
        cost: { wood: 100, minerals: 40 },
        prereq: ["fieldGuide"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          mineralsRateMul: 1.35,
          capMineralsAdd: 60,
        },
      },
      excavationTools: {
        name: "挖掘工具",
        desc: "进化石碎片产量 +40%，碎片上限 +80。",
        cost: { wood: 180, minerals: 90 },
        prereq: ["mineralSurvey"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          mineralsRateMul: 1.4,
          capMineralsAdd: 80,
        },
      },
      refining: {
        name: "精炼处理",
        desc: "进化石碎片产量 +20%，球果产量 +15%，碎片上限 +120。",
        cost: { wood: 260, minerals: 160 },
        prereq: ["excavationTools"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          mineralsRateMul: 1.2,
          woodRateMul: 1.15,
          capMineralsAdd: 120,
        },
      },
      oreStorage: {
        name: "储矿箱",
        desc: "球果上限 +120，进化石碎片上限 +200。",
        cost: { wood: 220, minerals: 180 },
        prereq: ["refining"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          capWoodAdd: 120,
          capMineralsAdd: 200,
        },
      },
      carpentry: {
        name: "木工训练",
        desc: "球果产量 +30%，球果上限 +80。",
        cost: { catnip: 220, wood: 60 },
        prereq: ["campLogistics"],
        req: (state) => state.buildings.hut.owned > 0,
        effects: {
          woodRateMul: 1.3,
          capWoodAdd: 80,
        },
      },
      sawmillPlans: {
        name: "锯木坊图纸",
        desc: "球果产量 +45%，球果上限 +160。",
        cost: { catnip: 500, wood: 200, minerals: 80 },
        prereq: ["carpentry"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          woodRateMul: 1.45,
          capWoodAdd: 160,
        },
      },
      supplyLines: {
        name: "补给线",
        desc: "树果/球果/碎片上限全面提升。",
        cost: { catnip: 800, wood: 300, minerals: 200 },
        prereq: ["sawmillPlans"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          capCatnipAdd: 120,
          capWoodAdd: 160,
          capMineralsAdd: 160,
        },
      },
      efficientConstruction: {
        name: "高效建造",
        desc: "营地建筑成本 -8%。",
        cost: { catnip: 1200, wood: 450, minerals: 300 },
        prereq: ["supplyLines"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          buildingCostMul: 0.92,
        },
      },
      advancedGear: {
        name: "高级装备",
        desc: "树果产量 +25%，并提升全部上限。",
        cost: { catnip: 900, wood: 250, minerals: 150 },
        prereq: ["efficientConstruction"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          catnipPerSecMul: 1.25,
          capCatnipAdd: 60,
          capWoodAdd: 120,
          capMineralsAdd: 90,
          catchChanceAdd: 0.05,
        },
      },
      researchMethod: {
        name: "研究方法",
        desc: "树果/球果/碎片产量 +15%。",
        cost: { catnip: 1500, wood: 600, minerals: 400 },
        prereq: ["advancedGear"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          catnipPerSecMul: 1.15,
          woodRateMul: 1.15,
          mineralsRateMul: 1.15,
        },
      },
      ultraStorage: {
        name: "超大容量仓储",
        desc: "大幅提升所有资源上限。",
        cost: { catnip: 2500, wood: 900, minerals: 700 },
        prereq: ["researchMethod"],
        req: (state) => state.buildings.workshop.owned > 0,
        effects: {
          capCatnipAdd: 300,
        },
      }
};
